# Generated by Django 4.2.8 on 2024-01-07 07:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import djangocms_attributes_field.fields
import filer.fields.image
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fighters_id', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_crown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fighter_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('career_years', models.CharField(blank=True, default='2023-2023', max_length=9, null=True)),
                ('name', models.CharField(default='Unknown', max_length=100, unique=True, verbose_name='fighter name')),
                ('score', models.IntegerField(default=0, verbose_name='fighter score')),
                ('weight_class', models.CharField(choices=[('SUPER_HEAVY', 'Super Heavy'), ('HEAVY', 'Heavy'), ('CRUISER', 'Cruiser'), ('LIGHT_HEAVY', 'Light Heavy'), ('SUPER_MIDDLE', 'Super Middle'), ('MIDDLE', 'Middle'), ('SUPER_WELTER', 'Super Welter'), ('WELTER', 'Welter'), ('SUPER_LIGHT', 'Super Light'), ('LIGHT', 'Light'), ('SUPER_FEATHER', 'Super Feather'), ('FEATHER', 'Feather'), ('SUPER_BANTAM', 'Super Bantam'), ('BANTAM', 'Bantam'), ('SUPER_FLY', 'Super Fly'), ('FLY', 'Fly'), ('LIGHT_FLY', 'Light Fly'), ('MINIMUM', 'Minimum'), ('ATOM', 'Atom'), ('OTHER', 'Other')], default='LIGHT', max_length=20, verbose_name='weight class')),
                ('height', models.CharField(blank=True, max_length=20, verbose_name='height')),
                ('weight', models.IntegerField(blank=True, default=0, null=True, verbose_name='fighter weight')),
                ('sport', models.CharField(choices=[('UFC', 'UFC'), ('MMA', 'MMA'), ('KICKBOXING_PRO', 'Kickboxing Pro'), ('KICKBOXING_AMATEUR', 'Kickboxing Amateur'), ('MUAY_THAI', 'Muay Thai'), ('FREE_FIGHTING', 'Free Fighting'), ('BOXING_PRO', 'Boxing Pro'), ('BOXING_AMATEUR', 'Boxing Amateur'), ('KARATE', 'Karate'), ('OTHER', 'Other')], default='UFC', max_length=100, verbose_name='sport')),
                ('champion', models.CharField(choices=[('UFC', 'UFC'), ('MMA', 'MMA'), ('KICKBOXING_PRO', 'Kickboxing Pro'), ('KICKBOXING_AMATEUR', 'Kickboxing Amateur'), ('MUAY_THAI', 'Muay Thai'), ('FREE_FIGHTING', 'Free Fighting'), ('BOXING_PRO', 'Boxing Pro'), ('BOXING_AMATEUR', 'Boxing Amateur'), ('KARATE', 'Karate'), ('OTHER', 'Other'), ('NOT_HAVE', 'Not Have')], default='UFC', max_length=20, verbose_name='Champion')),
                ('champion_des', models.CharField(default='Unknown', max_length=20, verbose_name='champion description')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, null=True)),
                ('nationality', django_countries.fields.CountryField(default='US', max_length=2, null=True)),
                ('residence', django_countries.fields.CountryField(default='US', max_length=2, null=True)),
                ('titles', models.CharField(choices=[('NOT_HAVE', 'Not Have'), ('M  |UFC', 'M | UFC'), ('F|UFC', 'F | UFC'), ('M|U.S.REGIONAL MMA', 'M | U.S. Regional MMA'), ('F|U.S.REGIONAL MMA', 'F | U.S. Regional MMA'), ('F|UFC', 'F | UFC'), ('M|IBF African', 'M | IBF African'), ('M|IBF Asia', 'M | IBF Asia'), ('M|IBF Asia Oceania', 'M | IBF Asia Oceania'), ('M|IBF Australasian', 'M | IBF Australasian'), ('M|IBF European', 'M | IBF European'), ('M|IBF European E/W', 'M | IBF European E/W'), ('M|IBF Inter-Continental', 'M | IBF Inter-Continental'), ('f|IBF Inter-Continental', 'f | IBF Inter-Continental'), ('M|IBF Interi M World', 'M | IBF Interi M World'), ('f|IBF Interi M World', 'f | IBF Interi M World'), ('M|IBF International', 'M | IBF International'), ('M|IBF Latino', 'M | IBF Latino'), ('M|IBF Mediterranean', 'M | IBF Mediterranean'), ('M|IBF North A Merican', 'M | IBF North A Merican'), ('M|IBF Pan Pacific', 'M | IBF Pan Pacific'), ('M|IBF USBA', 'M | IBF USBA'), ('M|IBF USBA Atlantic Coast Region', 'M | IBF USBA Atlantic Coast Region'), ('M|IBF USBA Southern Region', 'M | IBF USBA Southern Region'), ('M|IBF World', 'M | IBF World'), ('f|IBF World', 'f | IBF World'), ('M|IBF Youth', 'M | IBF Youth'), ('M|IBO All-Africa', 'M | IBO All-Africa'), ('M|IBO A Mericas', 'M | IBO A Mericas'), ('M|IBO Asia Pacific', 'M | IBO Asia Pacific'), ('M|IBO Continental', 'M | IBO Continental'), ('M|IBO European', 'M | IBO European'), ('M|IBO IberoA Merican', 'M | IBO IberoA Merican'), ('M|IBO Inter-Continental', 'M | IBO Inter-Continental'), ('f|IBO Inter-Continental', 'f | IBO Inter-Continental'), ('M|IBO International', 'M | IBO International'), ('f|IBO International', 'f | IBO International'), ('M|IBO Mediterranean', 'M | IBO Mediterranean'), ('M|IBO Oceania-Orient', 'M | IBO Oceania-Orient'), ('M|IBO World', 'M | IBO World'), ('f|IBO World', 'f | IBO World'), ('M|IBO World Youth', 'M | IBO World Youth'), ('f|IBO World Youth', 'f | IBO World Youth'), ('M|WBA Fedebol', 'M | WBA Fedebol'), ('M|WBA Fedecaribe', 'M | WBA Fedecaribe'), ('M|WBA Fedecentro', 'M | WBA Fedecentro'), ('M|WBA Fedelatin', 'M | WBA Fedelatin'), ('f|WBA Fedelatin', 'f | WBA Fedelatin'), ('M|WBA Gold World', 'M | WBA Gold World'), ('f|WBA Gold World', 'f | WBA Gold World'), ('M|WBA Inter-Continental', 'M | WBA Inter-Continental'), ('f|WBA Inter-Continental', 'f | WBA Inter-Continental'), ('M|WBA Interi M World', 'M | WBA Interi M World'), ('f|WBA Interi M World', 'f | WBA Interi M World'), ('M|WBA Super World', 'M | WBA Super World'), ('f|WBA Super World', 'f | WBA Super World'), ('M|WBA World', 'M  |WBA World'), ('f|WBA World', 'f | WBA World'), ('M|WBC Asian', 'M | WBC Asian'), ('M|WBC Asian Continental', 'M | WBC Asian Continental'), ('M|WBC Asian Silver', 'M|WBC Asian Silver'), ('M|WBC CISBB', 'M | WBC CISBB'), ('M|WBC Continental A Mericas', 'M | WBC Continental A Mericas'), ('M|WBC Dia Mond', 'M | WBC Dia Mond'), ('f|WBC Dia Mond', 'f  |WBC Dia Mond'), ('M|WBC FECARBOX', 'M | WBC FECARBOX'), ('M|WBC FECONSUR', 'M | WBC FECONSUR'), ('f|WBC FECONSUR', 'f | WBC FECONSUR'), ('M|WBC Francophone', 'M | WBC Francophone'), ('f|WBC Francophone', 'f | WBC Francophone'), ('M|WBC Interi M World', 'M | WBC Interi M World'), ('f|WBC Interi M World', 'f | WBC Interi M World'), ('M|WBC International', 'M | WBC International'), ('f|WBC International', 'f | WBC International'), ('M|WBC International Silver', 'M | WBC International Silver'), ('M|WBC Latino', 'M | WBC Latino'), ('f|WBC Latino', 'f | WBC Latino'), ('M|WBC Mediterranean', 'M | WBC Mediterranean'), ('M|WBC Silver', 'M | WBC Silver'), ('f|WBC Silver', 'f | WBC Silver'), ('M|WBC USA', 'M | WBC USA'), ('M|WBC USA Silver', 'M | WBC USA Silver'), ('M|WBC World', 'M | WBC World'), ('f|WBC World', 'f | WBC World'), ('M|WBC Youth Intercontinental', 'M | WBC Youth Intercontinental'), ('M|WBC Youth Silver', 'M | WBC Youth Silver'), ('M|WBC Youth World', 'M | WBC Youth World'), ('f|WBC Youth World', 'f | WBC Youth World'), ('M|WBO Africa', 'M | WBO Africa'), ('M|WBO Asia Pacific', 'M | WBO Asia Pacific'), ('W|WBO Asia Pacific', 'W | WBO Asia Pacific'), ('M|WBO Asia Pacific Youth', 'M | WBO Asia Pacific Youth'), ('M|WBO Chinese', 'M | WBO Chinese'), ('M|WBO European', 'M | WBO European'), ('M|WBO Global', 'M | WBO Global'), ('M|WBO Inter-Continental', 'M | WBO Inter-Continental'), ('M|WBO Interi M World', 'M | WBO Interi M World'), ('f|WBO Interi M World', 'f | WBO Interi M World'), ('M|WBO International', 'M | WBO International'), ('M|WBO Latino', 'M | WBO Latino'), ('M|WBO NABO', 'M | WBO NABO'), ('M|WBO NABO Youth', 'M | WBO NABO Youth'), ('1 M|WBO Oriental', '1 M | WBO Oriental'), ('M|WBO Oriental Youth', 'M | WBO Oriental Youth'), ('M|WBO World', 'M | WBO World'), ('f|WBO World', 'f | WBO World'), ('M|WBO Youth', 'M | WBO Youth'), ('M|Asian Boxing Federation', 'M  |Asian Boxing Federation'), ('f|Asian Boxing Federation', 'f | Asian Boxing Federation'), ('M|Australasian', 'M | Australasian'), ('f|Australasian', 'f | Australasian'), ('Australian National Boxing Federation NeW South Wales', 'Australian National Boxing Federation NeW South Wales'), ('M|Australian National Boxing Federation NeW South Wales', 'M | Australian National Boxing Federation NeW South Wales'), ('f|Australian National Boxing Federation NeW South Wales', 'f | Australian National Boxing Federation NeW South Wales'), ('Australian National Boxing Federation Queensland', 'Australian National Boxing Federation Queensland'), ('M|Australian National Boxing Federation Queensland', 'M | Australian National Boxing Federation Queensland'), ('f|Australian National Boxing Federation Queensland', 'f | Australian National Boxing Federation Queensland'), ('Belgian Boxing FederationW', 'Belgian Boxing FederationW'), ('f|Belgian Boxing Federation', 'f | Belgian Boxing Federation'), ('M|Belgian', 'M | Belgian'), ('Boxing South Africa', 'Boxing South Africa'), ('M|South African', 'M | South African'), ('f|South African', 'f | South African'), ('Boxing Union of Ireland', 'Boxing Union of Ireland'), ('M|Celtic', 'M | Celtic'), ('M|Irish', 'M  |Irish'), ('British Boxing Board of Control', 'British Boxing Board of Control'), ('M|BBBofC British', 'M | BBBofC British'), ('f|BBBofC British', 'f | BBBofC British'), ('M|BBBofC Celtic', 'M | BBBofC Celtic'), ('f|BBBofC Celtic', 'f | BBBofC Celtic'), ('M|BBBofC Central Area', 'M | BBBofC Central Area'), ('f|BBBofC Central Area', 'f | BBBofC Central Area'), ('M|BBBofC English', 'M | BBBofC English'), ('f|BBBofC English', 'f | BBBofC English'), ('M|BBBofC Midlands Area', 'M | BBBofC Midlands Area'), ('f|BBBofC Midlands Area', 'f | BBBofC Midlands Area'), ('M|BBBofC Northern Area', 'M | BBBofC Northern Area'), ('f|BBBofC Northern Area', 'f | BBBofC Northern Area'), ('M|BBBofC Northern Ireland Area', 'M | BBBofC Northern Ireland Area'), ('f|BBBofC Northern Ireland Area', 'f | BBBofC Northern Ireland Area'), ('M|BBBofC Scottish Area', 'M | BBBofC Scottish Area'), ('f|BBBofC Scottish Area', 'f | BBBofC Scottish Area'), ('M|BBBofC Southern Area', 'M | BBBofC Southern Area'), ('f|BBBofC Southern Area', 'f |BBBofC Southern Area'), ('M|BBBofC Welsh Area', 'M | BBBofC Welsh Area'), ('f|BBBofC Welsh Area', 'f | BBBofC Welsh Area'), ('M|BBBofC Western Area', 'M | BBBofC Western Area'), ('M|BDB Ger Man', 'M | BDB Ger Man'), ('M|BDB International', 'M | BDB International'), ('M|Co M MonWealth Boxing Council', 'M | Co M MonWealth Boxing Council'), ('f|Co M MonWealth Boxing Council', 'f | Co M MonWealth Boxing Council'), ('M|Eurasian Boxing Parlia Ment', 'M | Eurasian Boxing Parlia Ment'), ('f|Eurasian Boxing Parlia Ment', 'f | Eurasian Boxing Parlia Ment'), ('M|EBU European', 'M | EBU European'), ('f|EBU European', 'f | EBU European'), ('M|EBU European Union', 'M | EBU European Union'), ('M|EBU External', 'M | EBU External'), ('M|EBU Silver', 'M | EBU Silver'), ('M|Argentinian', 'M | Argentinian'), ('f|Argentinian', 'f | Argentinian'), ('M|French', 'M | French'), ('f|French', 'f | French'), ('M|Federazione Pugilistica Italiana', 'M | Federazione Pugilistica Italiana'), ('f|Federazione Pugilistica Italiana', 'f | Federazione Pugilistica Italiana'), ('M|International', 'M | International'), ('M|National', 'M | National'), ('M|Intercontinental', 'M | Intercontinental'), ('M|World', 'M | World'), ('f|World', 'f | World'), ('M|World Youth', 'M | World Youth'), ('M|WKF', 'M | WKF'), ('f|WKF', 'f | WKF'), ('M|WAKO', 'M | WAKO'), ('W|WAKO', 'W | WAKO'), ('M|ONE Champion', 'M | ONE Champion'), ('W|ONE Champion', 'W | ONE Champion'), ('M|WKA', 'M | WKA'), ('W|WKA', 'W | WKA'), ('M|GLORY', 'M | GLORY'), ('W|GLORY', 'W | GLORY'), ('M|RING20 KB', 'M | RING20 KB'), ('W|RING20 KB', 'W | RING20 KB'), ('M|WKB', 'M | WKB'), ('W|WKB', 'W | WKB'), ('M|WMC', 'M | WMC'), ('W|WMC', 'W | WMC'), ('M|WMF', 'M | WMF'), ('W|WMF', 'W | WMF'), ('M|WBC', 'M | WBC'), ('W|WBC', 'W  |WBC'), ('M|IFMA', 'M | IFMA'), ('W|IFMA', 'W | IFMA'), ('M|RING20 MT', 'M | RING20 MT'), ('W|RING20 MT', 'W | RING20 MT'), ('M|WMT', 'M | WMT'), ('W|WMT', 'W | WMT'), ('M|IKS', 'M  |IKS'), ('W|IKS', 'W | IKS'), ('M|WKF', 'M | WKF'), ('W|WKF', 'W | WKF'), ('M|IKF', 'M | IKF'), ('W|IKF', 'W | IKF'), ('M|ISKA', 'M | ISKA'), ('W|ISKA', 'W | ISKA'), ('M|RING20 K', 'M | RING20 K'), ('W|RING20 K', 'W | RING20 K'), ('OTHER', 'other')], default='Not Have', max_length=100, verbose_name='fighter titles')),
                ('bouts', models.IntegerField(blank=True, default=0, verbose_name='fighter bouts')),
                ('rounds', models.IntegerField(blank=True, default=0, verbose_name='fighter rounds')),
                ('wins', models.IntegerField(blank=True, default=0, verbose_name='fighter win')),
                ('losses', models.IntegerField(blank=True, default=0, verbose_name='fighter losses')),
                ('draws', models.IntegerField(blank=True, default=0, verbose_name='fighter draws')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=5, verbose_name='fighter gender')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='fighter age')),
                ('star_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
            ],
        ),
        migrations.CreateModel(
            name='FighterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100, null=True, unique=True, verbose_name='fighter category')),
            ],
        ),
        migrations.CreateModel(
            name='FighterManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100, null=True, unique=True, verbose_name='fighter manager')),
            ],
        ),
        migrations.CreateModel(
            name='FighterPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('weight_class', models.CharField(blank=True, max_length=255)),
                ('sport', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('champion', models.CharField(blank=True, max_length=255)),
                ('fighter_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fighter.fighter')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FighterDetailPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('fighter_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fighter.fighter')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='fighter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fighter.fightercategory'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='fighter_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fighter.fightermanager'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL, verbose_name='fighter image'),
        ),
    ]
