# Generated by Django 4.2.4 on 2024-01-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='champion',
            new_name='champion_fighter',
        ),
        migrations.RenameField(
            model_name='fighter',
            old_name='country',
            new_name='country_fighter',
        ),
        migrations.RenameField(
            model_name='fighter',
            old_name='gender',
            new_name='gender_fighter',
        ),
        migrations.RenameField(
            model_name='fighter',
            old_name='sport',
            new_name='sport_fighter',
        ),
        migrations.RenameField(
            model_name='fighter',
            old_name='titles',
            new_name='title_fighter',
        ),
        migrations.RenameField(
            model_name='fighter',
            old_name='weight_class',
            new_name='weight_class_fighter',
        ),
    ]
