# Generated by Django 4.2.8 on 2024-01-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fighter.fightercategory'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='fighter_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fighter.fightermanager'),
        ),
    ]
